### ISSUE TITLE
 Firebase config object

### ISSUE THREAD

**Issue by loganthomison** [ash2osh/firebase-auth-wordpress#1]
What are the appropriate values for the firebase config object? Something like the following?

    apiKey: "<API_KEY>",
    authDomain: "<PROJECT_ID>.firebaseapp.com",
    databaseURL: "https://<DATABASE_NAME>.firebaseio.com",

**Comment by ash2osh** [comment]
{
    apiKey: "xxxxx",
    authDomain: "xxxxx.firebaseapp.com",
    databaseURL: "https://xxxxx.firebaseio.com",
    projectId: "xxxxx",
    storageBucket: "xxxxxx.appspot.com",
    messagingSenderId: "nnnnnn"
  }
